In [1]:
import numpy as np
import PIL

import torch

In [2]:
from fastai.vision import Image

In [3]:
def pil2tensor(image,dtype):
    "Convert PIL style `image` array to torch style image tensor."
    a = np.asarray(image)
    if a.ndim==2 : a = np.expand_dims(a,2)
    a = np.transpose(a, (1, 0, 2))
    a = np.transpose(a, (2, 1, 0))
    return torch.from_numpy(a.astype(dtype, copy=False) )

In [4]:
filename = '/home/santhosr/Documents/Birad/ProcessedData/./FullRes/2/76876308_R_MLO_1.jpg'

x = PIL.Image.open(filename).convert('RGB')

x = pil2tensor(x,np.float32)

x.div_(255)   

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

In [5]:
out = Image(x)

In [6]:
out.shape

torch.Size([3, 4096, 3328])

In [9]:
import fastai
from fastai.vision import *
from fastai.callbacks import *
from fastai.torch_core import *
from fastai.callback import *
from fastai.basic_train import *
import torchvision.models as tmodels

import pandas as pd
import numpy as np
import os
from tqdm import tqdm
from sklearn.metrics import accuracy_score
from scipy.misc import imsave

from sklearn.metrics import accuracy_score, auc, roc_auc_score, roc_curve
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import cross_val_score
from scipy.misc import imsave

import torchvision
from torch.nn import Sigmoid
from torch import Tensor, LongTensor
from torch.autograd import Variable
import torch.nn as nn
import torch
import torch.nn.functional as F
import torchvision.transforms as transforms
from torch.nn import Sequential
from torchvision.models.resnet import resnet50





import os
import sys

sys.path.insert(0, '/home/santhosr/Documents/Birad/FastAI/RaceClassification/' )

from utils import *

from birad import *
from birad import setTruthFile, getRaceLabel


inputFolder1 = '/home/santhosr/Documents/Birad/ProcessedData/FullRes'
truthFile1 = '/home/santhosr/Documents/Birad/birad_targetFile.csv'

inputFolder2 = '/home/santhosr/Documents/Birad/ProcessedData/PennExtra_3500/'
truthFile2 = '/home/santhosr/Documents/Birad/RaceDL_ExtraCaucasian.csv'

df1 = pd.read_csv('/home/santhosr/Documents/Birad/birad_targetFile.csv')
df1.drop(['PresIntentType','DBT'],inplace = True,axis=1)


df2 = pd.read_csv('/home/santhosr/Documents/Birad/RaceDL_ExtraCaucasian.csv')
df2.Medview_Race = 'White'
truth = pd.concat([df1,df2],sort=True)

setTruthFile(truth)


dfFile = "/home/santhosr/Documents/Birad/FastAI/RaceClassification/withLargerDataset/DataFile10.csv"

modelName = 'model_resnet50_id10_acc833_loss386'


#Feature Directories
trainFolder = '/home/santhosr/Documents/Birad/FastAI/RaceClassification/withLargerDataset/Features/model9_2/train'

validFolder = '/home/santhosr/Documents/Birad/FastAI/RaceClassification/withLargerDataset/Features/model9_2/valid'

df = pd.read_csv(dfFile)

In [ ]:
d = pd.concat([df[df.train==True].iloc[0:100], df[df.train==False].iloc[0:100], ])

#Creates the FastAI Dataset
data = ImageItemList.from_df(df=d,path='/home/santhosr/Documents/Birad/ProcessedData/', cols='filename').split_from_df(col='train').label_from_func(getRaceLabel).transform(get_transforms(),size=256).databunch(bs=50).normalize()
print("Dataset created")

In [28]:
tp = data.one_item(out)

(tensor([[[[-1.8236e+00, -1.8236e+00, -1.8286e+00,  ...,  7.2550e-01,
             7.2550e-01,  7.2550e-01],
           [-1.8154e+00, -1.8166e+00, -1.8191e+00,  ...,  7.2550e-01,
             7.2550e-01,  7.2550e-01],
           [-1.8254e+00, -1.8304e+00, -1.8228e+00,  ...,  7.2550e-01,
             7.2550e-01,  7.2550e-01],
           ...,
           [-1.9489e-01, -3.2107e-01, -1.0758e-01,  ...,  7.2550e-01,
             7.2550e-01,  7.2550e-01],
           [-7.3464e-02, -8.2342e-02, -5.0757e-04,  ...,  7.2550e-01,
             7.2550e-01,  7.2550e-01],
           [ 1.7083e-01, -1.2072e-02,  8.2581e-02,  ...,  7.2550e-01,
             7.2550e-01,  7.2550e-01]],
 
          [[-1.8236e+00, -1.8236e+00, -1.8286e+00,  ...,  7.2550e-01,
             7.2550e-01,  7.2550e-01],
           [-1.8154e+00, -1.8166e+00, -1.8191e+00,  ...,  7.2550e-01,
             7.2550e-01,  7.2550e-01],
           [-1.8254e+00, -1.8304e+00, -1.8228e+00,  ...,  7.2550e-01,
             7.2550e-01,  7.2550e-01],


In [71]:
ds = data.single_ds

In [75]:
with ds.set_item(out):
#     batch =  data.one_batch(ds_type=DatasetType.Single, detach=False, denorm=False)
    
    dl = data.dl(DatasetType.Single)
    
    it = iter(dl)
    
#     x,y = next(it)
    
#     print(x)

In [35]:
DatasetType = Enum('DatasetType', 'Train Valid Test Single Fix')

In [52]:
dl = data.dl(DatasetType.Single)

In [53]:
it = iter(dl)

In [54]:
x,y = next(it)

In [55]:
x

tensor([[[[-1.7724, -1.7735, -1.7530,  ...,  0.7255,  0.7255,  0.7255],
          [-1.7573, -1.7706, -1.7515,  ...,  0.7255,  0.7255,  0.7255],
          [-1.7430, -1.7759, -1.7443,  ...,  0.7255,  0.7255,  0.7255],
          ...,
          [ 0.7255,  0.7255,  0.7255,  ...,  0.7255,  0.7255,  0.7255],
          [ 0.7255,  0.7255,  0.7255,  ...,  0.7255,  0.7255,  0.7255],
          [ 0.7255,  0.7255,  0.7255,  ...,  0.7255,  0.7255,  0.7255]],

         [[-1.7724, -1.7735, -1.7530,  ...,  0.7255,  0.7255,  0.7255],
          [-1.7573, -1.7706, -1.7515,  ...,  0.7255,  0.7255,  0.7255],
          [-1.7430, -1.7759, -1.7443,  ...,  0.7255,  0.7255,  0.7255],
          ...,
          [ 0.7255,  0.7255,  0.7255,  ...,  0.7255,  0.7255,  0.7255],
          [ 0.7255,  0.7255,  0.7255,  ...,  0.7255,  0.7255,  0.7255],
          [ 0.7255,  0.7255,  0.7255,  ...,  0.7255,  0.7255,  0.7255]],

         [[-1.7724, -1.7735, -1.7530,  ...,  0.7255,  0.7255,  0.7255],
          [-1.7573, -1.7706, -

In [63]:
import pdb

In [ ]:
pdb.run('x,y = next(it)')

> <string>(1)<module>()->None
(Pdb) s
--Call--
> /home/santhosr/.local/lib/python3.6/site-packages/fastai/basic_data.py(68)__iter__()
-> def __iter__(self):
(Pdb) s
> /home/santhosr/.local/lib/python3.6/site-packages/fastai/basic_data.py(70)__iter__()
-> for b in self.dl: yield self.proc_batch(b)
(Pdb) s
--Call--
> /home/santhosr/.conda/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py(818)__iter__()
-> def __iter__(self):
(Pdb) s
> /home/santhosr/.conda/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py(819)__iter__()
-> return _DataLoaderIter(self)
(Pdb) n


Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7faa8138aeb8>>
Traceback (most recent call last):
  File "/home/santhosr/.conda/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
  File "/home/santhosr/.conda/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/santhosr/.conda/envs/fastai/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process


--Return--
> /home/santhosr/.conda/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py(819)__iter__()-><torch.utils....x7faa80c95cf8>
-> return _DataLoaderIter(self)


Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7faa8138aeb8>>
Traceback (most recent call last):
  File "/home/santhosr/.conda/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
  File "/home/santhosr/.conda/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/santhosr/.conda/envs/fastai/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7faa8138aeb8>>
Traceback (most recent call last):
  File "/home/santhosr/.conda/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._s

(Pdb) n
--Call--
> /home/santhosr/.conda/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py(612)__next__()
-> def __next__(self):
(Pdb) s
> /home/santhosr/.conda/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py(613)__next__()
-> if self.num_workers == 0:  # same-process loading
(Pdb) ll
612  	    def __next__(self):
613  ->	        if self.num_workers == 0:  # same-process loading
614  	            indices = next(self.sample_iter)  # may raise StopIteration
615  	            batch = self.collate_fn([self.dataset[i] for i in indices])
616  	            if self.pin_memory:
617  	                batch = pin_memory_batch(batch)
618  	            return batch
619  	
620  	        # check if the next sample has already been generated
621  	        if self.rcvd_idx in self.reorder_dict:
622  	            batch = self.reorder_dict.pop(self.rcvd_idx)
623  	            return self._process_next_batch(batch)
624  	
625  	        if self.batches_outstandin

In [59]:
help(torch.utils.data.dataloader.default_collate)

Help on function default_collate in module torch.utils.data.dataloader:

default_collate(batch)
    Puts each data field into a tensor with outer dimension batch size



In [62]:
print(inspect.getsource(torch.utils.data.dataloader.default_collate))

def default_collate(batch):
    r"""Puts each data field into a tensor with outer dimension batch size"""

    error_msg = "batch must contain tensors, numbers, dicts or lists; found {}"
    elem_type = type(batch[0])
    if isinstance(batch[0], torch.Tensor):
        out = None
        if _use_shared_memory:
            # If we're in a background process, concatenate directly into a
            # shared memory tensor to avoid an extra copy
            numel = sum([x.numel() for x in batch])
            storage = batch[0].storage()._new_shared(numel)
            out = batch[0].new(storage)
        return torch.stack(batch, 0, out=out)
    elif elem_type.__module__ == 'numpy' and elem_type.__name__ != 'str_' \
            and elem_type.__name__ != 'string_':
        elem = batch[0]
        if elem_type.__name__ == 'ndarray':
            # array of string classes and object
            if re.search('[SaUO]', elem.dtype.str) is not None:
                raise TypeError(error_msg.format(el